config:
  target: 'http://localhost:4000'
  phases:
    - duration: 2 # duración total 5 segundos
      arrivalRate: 1 # 1 usuario virtual por segundo
  plugins:
    metrics-by-endpoint: {}

scenarios:
  - name: "Autenticación de usuario"
    flow:
      - log: "Registrando usuario"
      - post:
          url: "/api/auth/register"
          json:
            firstName: "Tomas"
            lastName: "Zalazar"
            email: "tomaszalazar@gmail.com"
            password: "tomaszalazar"
          validate:
            - statusCode:
                - 201
            - body:
                - contains: "Usuario registrado exitosamente"

      - think: 2 # Espera de 2 segundos entre operaciones
      
      - log: "Iniciando sesión del usuario"
      - post:
          url: "/api/auth/login"
          json:
            email: "tomaszalazar@gmail.com"
            password: "tomaszalazar"
          validate:
            - statusCode:
                - 200
            - body:
                - contains: "Inicio de sesión exitoso"

      - think: 2
      
      - log: "Iniciando sesión con JWT"
      - post:
          url: "/api/auth/jwtlogin"
          json:
            email: "tomaszalazar@gmail.com"
            password: "tomaszalazar"
          validate:
            - statusCode:
                - 200
            - body:
                - contains: "Inicio de sesión exitoso"
          extract:
            json:
              token: "token"

      - think: 2
      
      - log: "Consultando información del usuario actual"
      - get:
          url: "/api/auth/current"
          headers:
            Authorization: "Bearer {{ token }}"
          validate:
            - statusCode:
                - 200
            - body:
                - contains: "user"

      - think: 2
      
      - log: "Cerrando sesión del usuario"
      - get:
          url: "/api/auth/logout"
          validate:
            - statusCode:
                - 200
